execute @s ~3 ~ ~3 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~2 ~ ~3 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~1 ~ ~3 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~0 ~ ~3 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~-1 ~ ~3 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~-2 ~ ~3 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~-3 ~ ~3 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~3 ~ ~2 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~2 ~ ~2 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~1 ~ ~2 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~0 ~ ~2 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~-1 ~ ~2 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~-2 ~ ~2 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~-3 ~ ~2 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~3 ~ ~1 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~2 ~ ~1 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~1 ~ ~1 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~0 ~ ~1 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~-1 ~ ~1 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~-2 ~ ~1 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~-3 ~ ~1 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~3 ~ ~ detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~2 ~ ~ detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~1 ~ ~ detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~-1 ~ ~ detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~-2 ~ ~ detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~-3 ~ ~ detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~3 ~ ~-1 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~2 ~ ~-1 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~1 ~ ~-1 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~0 ~ ~-1 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~-1 ~ ~-1 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~-2 ~ ~-1 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~-3 ~ ~-1 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~3 ~ ~-2 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~2 ~ ~-2 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~1 ~ ~-2 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~0 ~ ~-2 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~-1 ~ ~-2 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~-2 ~ ~-2 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~-3 ~ ~-2 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~3 ~ ~-3 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~2 ~ ~-3 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~1 ~ ~-3 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~0 ~ ~-3 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~-1 ~ ~-3 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~-2 ~ ~-3 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~-3 ~ ~-3 detect ~ ~ ~ beetroot 6 setblock ~~~ beetroot 7
execute @s ~3 ~ ~3 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~2 ~ ~3 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~1 ~ ~3 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~0 ~ ~3 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~-1 ~ ~3 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~-2 ~ ~3 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~-3 ~ ~3 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~3 ~ ~2 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~2 ~ ~2 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~1 ~ ~2 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~0 ~ ~2 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~-1 ~ ~2 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~-2 ~ ~2 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~-3 ~ ~2 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~3 ~ ~1 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~2 ~ ~1 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~1 ~ ~1 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~0 ~ ~1 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~-1 ~ ~1 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~-2 ~ ~1 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~-3 ~ ~1 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~3 ~ ~ detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~2 ~ ~ detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~1 ~ ~ detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~-1 ~ ~ detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~-2 ~ ~ detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~-3 ~ ~ detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~3 ~ ~-1 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~2 ~ ~-1 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~1 ~ ~-1 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~0 ~ ~-1 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~-1 ~ ~-1 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~-2 ~ ~-1 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~-3 ~ ~-1 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~3 ~ ~-2 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~2 ~ ~-2 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~1 ~ ~-2 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~0 ~ ~-2 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~-1 ~ ~-2 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~-2 ~ ~-2 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~-3 ~ ~-2 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~3 ~ ~-3 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~2 ~ ~-3 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~1 ~ ~-3 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~0 ~ ~-3 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~-1 ~ ~-3 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~-2 ~ ~-3 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~-3 ~ ~-3 detect ~ ~ ~ beetroot 5 setblock ~~~ beetroot 6
execute @s ~3 ~ ~3 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~2 ~ ~3 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~1 ~ ~3 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~0 ~ ~3 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~-1 ~ ~3 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~-2 ~ ~3 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~-3 ~ ~3 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~3 ~ ~2 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~2 ~ ~2 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~1 ~ ~2 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~0 ~ ~2 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~-1 ~ ~2 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~-2 ~ ~2 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~-3 ~ ~2 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~3 ~ ~1 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~2 ~ ~1 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~1 ~ ~1 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~0 ~ ~1 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~-1 ~ ~1 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~-2 ~ ~1 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~-3 ~ ~1 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~3 ~ ~ detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~2 ~ ~ detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~1 ~ ~ detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~-1 ~ ~ detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~-2 ~ ~ detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~-3 ~ ~ detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~3 ~ ~-1 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~2 ~ ~-1 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~1 ~ ~-1 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~0 ~ ~-1 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~-1 ~ ~-1 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~-2 ~ ~-1 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~-3 ~ ~-1 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~3 ~ ~-2 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~2 ~ ~-2 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~1 ~ ~-2 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~0 ~ ~-2 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~-1 ~ ~-2 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~-2 ~ ~-2 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~-3 ~ ~-2 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~3 ~ ~-3 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~2 ~ ~-3 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~1 ~ ~-3 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~0 ~ ~-3 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~-1 ~ ~-3 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~-2 ~ ~-3 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~-3 ~ ~-3 detect ~ ~ ~ beetroot 4 setblock ~~~ beetroot 5
execute @s ~3 ~ ~3 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~2 ~ ~3 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~1 ~ ~3 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~0 ~ ~3 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~-1 ~ ~3 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~-2 ~ ~3 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~-3 ~ ~3 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~3 ~ ~2 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~2 ~ ~2 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~1 ~ ~2 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~0 ~ ~2 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~-1 ~ ~2 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~-2 ~ ~2 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~-3 ~ ~2 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~3 ~ ~1 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~2 ~ ~1 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~1 ~ ~1 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~0 ~ ~1 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~-1 ~ ~1 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~-2 ~ ~1 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~-3 ~ ~1 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~3 ~ ~ detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~2 ~ ~ detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~1 ~ ~ detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~-1 ~ ~ detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~-2 ~ ~ detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~-3 ~ ~ detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~3 ~ ~-1 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~2 ~ ~-1 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~1 ~ ~-1 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~0 ~ ~-1 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~-1 ~ ~-1 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~-2 ~ ~-1 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~-3 ~ ~-1 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~3 ~ ~-2 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~2 ~ ~-2 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~1 ~ ~-2 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~0 ~ ~-2 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~-1 ~ ~-2 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~-2 ~ ~-2 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~-3 ~ ~-2 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~3 ~ ~-3 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~2 ~ ~-3 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~1 ~ ~-3 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~0 ~ ~-3 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~-1 ~ ~-3 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~-2 ~ ~-3 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~-3 ~ ~-3 detect ~ ~ ~ beetroot 3 setblock ~~~ beetroot 4
execute @s ~3 ~ ~3 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~2 ~ ~3 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~1 ~ ~3 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~0 ~ ~3 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~-1 ~ ~3 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~-2 ~ ~3 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~-3 ~ ~3 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~3 ~ ~2 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~2 ~ ~2 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~1 ~ ~2 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~0 ~ ~2 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~-1 ~ ~2 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~-2 ~ ~2 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~-3 ~ ~2 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~3 ~ ~1 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~2 ~ ~1 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~1 ~ ~1 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~0 ~ ~1 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~-1 ~ ~1 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~-2 ~ ~1 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~-3 ~ ~1 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~3 ~ ~ detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~2 ~ ~ detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~1 ~ ~ detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~-1 ~ ~ detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~-2 ~ ~ detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~-3 ~ ~ detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~3 ~ ~-1 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~2 ~ ~-1 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~1 ~ ~-1 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~0 ~ ~-1 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~-1 ~ ~-1 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~-2 ~ ~-1 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~-3 ~ ~-1 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~3 ~ ~-2 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~2 ~ ~-2 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~1 ~ ~-2 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~0 ~ ~-2 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~-1 ~ ~-2 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~-2 ~ ~-2 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~-3 ~ ~-2 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~3 ~ ~-3 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~2 ~ ~-3 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~1 ~ ~-3 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~0 ~ ~-3 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~-1 ~ ~-3 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~-2 ~ ~-3 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~-3 ~ ~-3 detect ~ ~ ~ beetroot 2 setblock ~~~ beetroot 3
execute @s ~3 ~ ~3 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~2 ~ ~3 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~1 ~ ~3 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~0 ~ ~3 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~-1 ~ ~3 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~-2 ~ ~3 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~-3 ~ ~3 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~3 ~ ~2 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~2 ~ ~2 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~1 ~ ~2 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~0 ~ ~2 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~-1 ~ ~2 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~-2 ~ ~2 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~-3 ~ ~2 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~3 ~ ~1 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~2 ~ ~1 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~1 ~ ~1 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~0 ~ ~1 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~-1 ~ ~1 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~-2 ~ ~1 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~-3 ~ ~1 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~3 ~ ~ detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~2 ~ ~ detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~1 ~ ~ detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~-1 ~ ~ detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~-2 ~ ~ detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~-3 ~ ~ detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~3 ~ ~-1 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~2 ~ ~-1 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~1 ~ ~-1 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~0 ~ ~-1 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~-1 ~ ~-1 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~-2 ~ ~-1 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~-3 ~ ~-1 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~3 ~ ~-2 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~2 ~ ~-2 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~1 ~ ~-2 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~0 ~ ~-2 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~-1 ~ ~-2 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~-2 ~ ~-2 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~-3 ~ ~-2 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~3 ~ ~-3 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~2 ~ ~-3 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~1 ~ ~-3 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~0 ~ ~-3 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~-1 ~ ~-3 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~-2 ~ ~-3 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~-3 ~ ~-3 detect ~ ~ ~ beetroot 1 setblock ~~~ beetroot 2
execute @s ~3 ~ ~3 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~2 ~ ~3 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~1 ~ ~3 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~0 ~ ~3 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~-1 ~ ~3 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~-2 ~ ~3 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~-3 ~ ~3 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~3 ~ ~2 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~2 ~ ~2 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~1 ~ ~2 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~0 ~ ~2 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~-1 ~ ~2 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~-2 ~ ~2 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~-3 ~ ~2 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~3 ~ ~1 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~2 ~ ~1 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~1 ~ ~1 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~0 ~ ~1 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~-1 ~ ~1 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~-2 ~ ~1 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~-3 ~ ~1 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~3 ~ ~ detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~2 ~ ~ detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~1 ~ ~ detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~-1 ~ ~ detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~-2 ~ ~ detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~-3 ~ ~ detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~3 ~ ~-1 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~2 ~ ~-1 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~1 ~ ~-1 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~0 ~ ~-1 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~-1 ~ ~-1 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~-2 ~ ~-1 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~-3 ~ ~-1 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~3 ~ ~-2 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~2 ~ ~-2 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~1 ~ ~-2 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~0 ~ ~-2 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~-1 ~ ~-2 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~-2 ~ ~-2 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~-3 ~ ~-2 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~3 ~ ~-3 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~2 ~ ~-3 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~1 ~ ~-3 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~0 ~ ~-3 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~-1 ~ ~-3 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~-2 ~ ~-3 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1
execute @s ~-3 ~ ~-3 detect ~ ~ ~ beetroot 0 setblock ~~~ beetroot 1