execute @s ~3 ~ ~3 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~2 ~ ~3 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~1 ~ ~3 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~0 ~ ~3 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~-1 ~ ~3 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~-2 ~ ~3 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~-3 ~ ~3 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~3 ~ ~2 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~2 ~ ~2 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~1 ~ ~2 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~0 ~ ~2 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~-1 ~ ~2 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~-2 ~ ~2 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~-3 ~ ~2 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~3 ~ ~1 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~2 ~ ~1 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~1 ~ ~1 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~0 ~ ~1 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~-1 ~ ~1 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~-2 ~ ~1 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~-3 ~ ~1 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~3 ~ ~ detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~2 ~ ~ detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~1 ~ ~ detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~-1 ~ ~ detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~-2 ~ ~ detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~-3 ~ ~ detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~3 ~ ~-1 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~2 ~ ~-1 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~1 ~ ~-1 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~0 ~ ~-1 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~-1 ~ ~-1 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~-2 ~ ~-1 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~-3 ~ ~-1 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~3 ~ ~-2 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~2 ~ ~-2 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~1 ~ ~-2 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~0 ~ ~-2 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~-1 ~ ~-2 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~-2 ~ ~-2 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~-3 ~ ~-2 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~3 ~ ~-3 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~2 ~ ~-3 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~1 ~ ~-3 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~0 ~ ~-3 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~-1 ~ ~-3 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~-2 ~ ~-3 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~-3 ~ ~-3 detect ~ ~ ~ carrots 6 setblock ~~~ carrots 7
execute @s ~3 ~ ~3 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~2 ~ ~3 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~1 ~ ~3 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~0 ~ ~3 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~-1 ~ ~3 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~-2 ~ ~3 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~-3 ~ ~3 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~3 ~ ~2 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~2 ~ ~2 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~1 ~ ~2 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~0 ~ ~2 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~-1 ~ ~2 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~-2 ~ ~2 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~-3 ~ ~2 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~3 ~ ~1 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~2 ~ ~1 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~1 ~ ~1 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~0 ~ ~1 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~-1 ~ ~1 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~-2 ~ ~1 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~-3 ~ ~1 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~3 ~ ~ detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~2 ~ ~ detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~1 ~ ~ detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~-1 ~ ~ detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~-2 ~ ~ detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~-3 ~ ~ detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~3 ~ ~-1 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~2 ~ ~-1 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~1 ~ ~-1 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~0 ~ ~-1 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~-1 ~ ~-1 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~-2 ~ ~-1 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~-3 ~ ~-1 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~3 ~ ~-2 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~2 ~ ~-2 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~1 ~ ~-2 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~0 ~ ~-2 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~-1 ~ ~-2 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~-2 ~ ~-2 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~-3 ~ ~-2 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~3 ~ ~-3 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~2 ~ ~-3 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~1 ~ ~-3 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~0 ~ ~-3 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~-1 ~ ~-3 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~-2 ~ ~-3 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~-3 ~ ~-3 detect ~ ~ ~ carrots 5 setblock ~~~ carrots 6
execute @s ~3 ~ ~3 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~2 ~ ~3 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~1 ~ ~3 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~0 ~ ~3 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~-1 ~ ~3 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~-2 ~ ~3 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~-3 ~ ~3 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~3 ~ ~2 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~2 ~ ~2 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~1 ~ ~2 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~0 ~ ~2 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~-1 ~ ~2 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~-2 ~ ~2 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~-3 ~ ~2 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~3 ~ ~1 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~2 ~ ~1 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~1 ~ ~1 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~0 ~ ~1 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~-1 ~ ~1 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~-2 ~ ~1 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~-3 ~ ~1 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~3 ~ ~ detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~2 ~ ~ detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~1 ~ ~ detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~-1 ~ ~ detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~-2 ~ ~ detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~-3 ~ ~ detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~3 ~ ~-1 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~2 ~ ~-1 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~1 ~ ~-1 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~0 ~ ~-1 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~-1 ~ ~-1 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~-2 ~ ~-1 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~-3 ~ ~-1 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~3 ~ ~-2 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~2 ~ ~-2 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~1 ~ ~-2 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~0 ~ ~-2 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~-1 ~ ~-2 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~-2 ~ ~-2 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~-3 ~ ~-2 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~3 ~ ~-3 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~2 ~ ~-3 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~1 ~ ~-3 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~0 ~ ~-3 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~-1 ~ ~-3 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~-2 ~ ~-3 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~-3 ~ ~-3 detect ~ ~ ~ carrots 4 setblock ~~~ carrots 5
execute @s ~3 ~ ~3 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~2 ~ ~3 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~1 ~ ~3 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~0 ~ ~3 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~-1 ~ ~3 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~-2 ~ ~3 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~-3 ~ ~3 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~3 ~ ~2 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~2 ~ ~2 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~1 ~ ~2 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~0 ~ ~2 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~-1 ~ ~2 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~-2 ~ ~2 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~-3 ~ ~2 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~3 ~ ~1 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~2 ~ ~1 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~1 ~ ~1 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~0 ~ ~1 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~-1 ~ ~1 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~-2 ~ ~1 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~-3 ~ ~1 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~3 ~ ~ detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~2 ~ ~ detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~1 ~ ~ detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~-1 ~ ~ detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~-2 ~ ~ detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~-3 ~ ~ detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~3 ~ ~-1 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~2 ~ ~-1 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~1 ~ ~-1 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~0 ~ ~-1 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~-1 ~ ~-1 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~-2 ~ ~-1 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~-3 ~ ~-1 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~3 ~ ~-2 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~2 ~ ~-2 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~1 ~ ~-2 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~0 ~ ~-2 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~-1 ~ ~-2 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~-2 ~ ~-2 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~-3 ~ ~-2 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~3 ~ ~-3 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~2 ~ ~-3 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~1 ~ ~-3 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~0 ~ ~-3 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~-1 ~ ~-3 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~-2 ~ ~-3 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~-3 ~ ~-3 detect ~ ~ ~ carrots 3 setblock ~~~ carrots 4
execute @s ~3 ~ ~3 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~2 ~ ~3 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~1 ~ ~3 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~0 ~ ~3 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~-1 ~ ~3 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~-2 ~ ~3 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~-3 ~ ~3 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~3 ~ ~2 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~2 ~ ~2 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~1 ~ ~2 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~0 ~ ~2 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~-1 ~ ~2 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~-2 ~ ~2 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~-3 ~ ~2 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~3 ~ ~1 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~2 ~ ~1 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~1 ~ ~1 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~0 ~ ~1 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~-1 ~ ~1 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~-2 ~ ~1 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~-3 ~ ~1 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~3 ~ ~ detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~2 ~ ~ detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~1 ~ ~ detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~-1 ~ ~ detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~-2 ~ ~ detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~-3 ~ ~ detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~3 ~ ~-1 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~2 ~ ~-1 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~1 ~ ~-1 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~0 ~ ~-1 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~-1 ~ ~-1 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~-2 ~ ~-1 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~-3 ~ ~-1 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~3 ~ ~-2 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~2 ~ ~-2 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~1 ~ ~-2 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~0 ~ ~-2 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~-1 ~ ~-2 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~-2 ~ ~-2 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~-3 ~ ~-2 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~3 ~ ~-3 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~2 ~ ~-3 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~1 ~ ~-3 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~0 ~ ~-3 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~-1 ~ ~-3 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~-2 ~ ~-3 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~-3 ~ ~-3 detect ~ ~ ~ carrots 2 setblock ~~~ carrots 3
execute @s ~3 ~ ~3 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~2 ~ ~3 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~1 ~ ~3 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~0 ~ ~3 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~-1 ~ ~3 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~-2 ~ ~3 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~-3 ~ ~3 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~3 ~ ~2 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~2 ~ ~2 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~1 ~ ~2 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~0 ~ ~2 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~-1 ~ ~2 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~-2 ~ ~2 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~-3 ~ ~2 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~3 ~ ~1 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~2 ~ ~1 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~1 ~ ~1 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~0 ~ ~1 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~-1 ~ ~1 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~-2 ~ ~1 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~-3 ~ ~1 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~3 ~ ~ detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~2 ~ ~ detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~1 ~ ~ detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~-1 ~ ~ detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~-2 ~ ~ detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~-3 ~ ~ detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~3 ~ ~-1 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~2 ~ ~-1 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~1 ~ ~-1 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~0 ~ ~-1 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~-1 ~ ~-1 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~-2 ~ ~-1 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~-3 ~ ~-1 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~3 ~ ~-2 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~2 ~ ~-2 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~1 ~ ~-2 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~0 ~ ~-2 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~-1 ~ ~-2 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~-2 ~ ~-2 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~-3 ~ ~-2 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~3 ~ ~-3 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~2 ~ ~-3 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~1 ~ ~-3 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~0 ~ ~-3 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~-1 ~ ~-3 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~-2 ~ ~-3 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~-3 ~ ~-3 detect ~ ~ ~ carrots 1 setblock ~~~ carrots 2
execute @s ~3 ~ ~3 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~2 ~ ~3 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~1 ~ ~3 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~0 ~ ~3 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~-1 ~ ~3 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~-2 ~ ~3 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~-3 ~ ~3 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~3 ~ ~2 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~2 ~ ~2 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~1 ~ ~2 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~0 ~ ~2 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~-1 ~ ~2 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~-2 ~ ~2 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~-3 ~ ~2 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~3 ~ ~1 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~2 ~ ~1 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~1 ~ ~1 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~0 ~ ~1 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~-1 ~ ~1 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~-2 ~ ~1 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~-3 ~ ~1 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~3 ~ ~ detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~2 ~ ~ detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~1 ~ ~ detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~-1 ~ ~ detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~-2 ~ ~ detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~-3 ~ ~ detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~3 ~ ~-1 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~2 ~ ~-1 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~1 ~ ~-1 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~0 ~ ~-1 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~-1 ~ ~-1 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~-2 ~ ~-1 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~-3 ~ ~-1 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~3 ~ ~-2 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~2 ~ ~-2 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~1 ~ ~-2 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~0 ~ ~-2 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~-1 ~ ~-2 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~-2 ~ ~-2 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~-3 ~ ~-2 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~3 ~ ~-3 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~2 ~ ~-3 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~1 ~ ~-3 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~0 ~ ~-3 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~-1 ~ ~-3 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~-2 ~ ~-3 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1
execute @s ~-3 ~ ~-3 detect ~ ~ ~ carrots 0 setblock ~~~ carrots 1