execute @s ~3 ~ ~3 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~2 ~ ~3 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~1 ~ ~3 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~0 ~ ~3 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~-1 ~ ~3 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~-2 ~ ~3 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~-3 ~ ~3 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~3 ~ ~2 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~2 ~ ~2 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~1 ~ ~2 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~0 ~ ~2 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~-1 ~ ~2 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~-2 ~ ~2 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~-3 ~ ~2 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~3 ~ ~1 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~2 ~ ~1 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~1 ~ ~1 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~0 ~ ~1 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~-1 ~ ~1 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~-2 ~ ~1 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~-3 ~ ~1 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~3 ~ ~ detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~2 ~ ~ detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~1 ~ ~ detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~-1 ~ ~ detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~-2 ~ ~ detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~-3 ~ ~ detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~3 ~ ~-1 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~2 ~ ~-1 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~1 ~ ~-1 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~0 ~ ~-1 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~-1 ~ ~-1 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~-2 ~ ~-1 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~-3 ~ ~-1 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~3 ~ ~-2 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~2 ~ ~-2 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~1 ~ ~-2 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~0 ~ ~-2 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~-1 ~ ~-2 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~-2 ~ ~-2 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~-3 ~ ~-2 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~3 ~ ~-3 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~2 ~ ~-3 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~1 ~ ~-3 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~0 ~ ~-3 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~-1 ~ ~-3 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~-2 ~ ~-3 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~-3 ~ ~-3 detect ~ ~ ~ potatoes 6 setblock ~~~ potatoes 7
execute @s ~3 ~ ~3 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~2 ~ ~3 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~1 ~ ~3 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~0 ~ ~3 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~-1 ~ ~3 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~-2 ~ ~3 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~-3 ~ ~3 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~3 ~ ~2 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~2 ~ ~2 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~1 ~ ~2 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~0 ~ ~2 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~-1 ~ ~2 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~-2 ~ ~2 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~-3 ~ ~2 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~3 ~ ~1 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~2 ~ ~1 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~1 ~ ~1 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~0 ~ ~1 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~-1 ~ ~1 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~-2 ~ ~1 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~-3 ~ ~1 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~3 ~ ~ detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~2 ~ ~ detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~1 ~ ~ detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~-1 ~ ~ detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~-2 ~ ~ detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~-3 ~ ~ detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~3 ~ ~-1 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~2 ~ ~-1 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~1 ~ ~-1 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~0 ~ ~-1 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~-1 ~ ~-1 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~-2 ~ ~-1 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~-3 ~ ~-1 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~3 ~ ~-2 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~2 ~ ~-2 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~1 ~ ~-2 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~0 ~ ~-2 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~-1 ~ ~-2 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~-2 ~ ~-2 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~-3 ~ ~-2 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~3 ~ ~-3 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~2 ~ ~-3 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~1 ~ ~-3 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~0 ~ ~-3 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~-1 ~ ~-3 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~-2 ~ ~-3 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~-3 ~ ~-3 detect ~ ~ ~ potatoes 5 setblock ~~~ potatoes 6
execute @s ~3 ~ ~3 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~2 ~ ~3 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~1 ~ ~3 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~0 ~ ~3 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~-1 ~ ~3 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~-2 ~ ~3 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~-3 ~ ~3 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~3 ~ ~2 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~2 ~ ~2 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~1 ~ ~2 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~0 ~ ~2 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~-1 ~ ~2 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~-2 ~ ~2 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~-3 ~ ~2 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~3 ~ ~1 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~2 ~ ~1 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~1 ~ ~1 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~0 ~ ~1 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~-1 ~ ~1 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~-2 ~ ~1 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~-3 ~ ~1 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~3 ~ ~ detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~2 ~ ~ detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~1 ~ ~ detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~-1 ~ ~ detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~-2 ~ ~ detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~-3 ~ ~ detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~3 ~ ~-1 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~2 ~ ~-1 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~1 ~ ~-1 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~0 ~ ~-1 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~-1 ~ ~-1 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~-2 ~ ~-1 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~-3 ~ ~-1 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~3 ~ ~-2 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~2 ~ ~-2 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~1 ~ ~-2 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~0 ~ ~-2 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~-1 ~ ~-2 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~-2 ~ ~-2 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~-3 ~ ~-2 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~3 ~ ~-3 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~2 ~ ~-3 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~1 ~ ~-3 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~0 ~ ~-3 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~-1 ~ ~-3 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~-2 ~ ~-3 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~-3 ~ ~-3 detect ~ ~ ~ potatoes 4 setblock ~~~ potatoes 5
execute @s ~3 ~ ~3 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~2 ~ ~3 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~1 ~ ~3 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~0 ~ ~3 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~-1 ~ ~3 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~-2 ~ ~3 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~-3 ~ ~3 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~3 ~ ~2 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~2 ~ ~2 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~1 ~ ~2 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~0 ~ ~2 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~-1 ~ ~2 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~-2 ~ ~2 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~-3 ~ ~2 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~3 ~ ~1 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~2 ~ ~1 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~1 ~ ~1 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~0 ~ ~1 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~-1 ~ ~1 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~-2 ~ ~1 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~-3 ~ ~1 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~3 ~ ~ detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~2 ~ ~ detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~1 ~ ~ detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~-1 ~ ~ detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~-2 ~ ~ detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~-3 ~ ~ detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~3 ~ ~-1 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~2 ~ ~-1 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~1 ~ ~-1 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~0 ~ ~-1 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~-1 ~ ~-1 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~-2 ~ ~-1 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~-3 ~ ~-1 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~3 ~ ~-2 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~2 ~ ~-2 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~1 ~ ~-2 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~0 ~ ~-2 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~-1 ~ ~-2 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~-2 ~ ~-2 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~-3 ~ ~-2 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~3 ~ ~-3 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~2 ~ ~-3 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~1 ~ ~-3 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~0 ~ ~-3 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~-1 ~ ~-3 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~-2 ~ ~-3 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~-3 ~ ~-3 detect ~ ~ ~ potatoes 3 setblock ~~~ potatoes 4
execute @s ~3 ~ ~3 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~2 ~ ~3 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~1 ~ ~3 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~0 ~ ~3 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~-1 ~ ~3 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~-2 ~ ~3 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~-3 ~ ~3 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~3 ~ ~2 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~2 ~ ~2 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~1 ~ ~2 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~0 ~ ~2 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~-1 ~ ~2 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~-2 ~ ~2 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~-3 ~ ~2 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~3 ~ ~1 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~2 ~ ~1 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~1 ~ ~1 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~0 ~ ~1 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~-1 ~ ~1 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~-2 ~ ~1 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~-3 ~ ~1 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~3 ~ ~ detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~2 ~ ~ detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~1 ~ ~ detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~-1 ~ ~ detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~-2 ~ ~ detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~-3 ~ ~ detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~3 ~ ~-1 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~2 ~ ~-1 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~1 ~ ~-1 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~0 ~ ~-1 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~-1 ~ ~-1 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~-2 ~ ~-1 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~-3 ~ ~-1 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~3 ~ ~-2 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~2 ~ ~-2 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~1 ~ ~-2 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~0 ~ ~-2 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~-1 ~ ~-2 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~-2 ~ ~-2 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~-3 ~ ~-2 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~3 ~ ~-3 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~2 ~ ~-3 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~1 ~ ~-3 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~0 ~ ~-3 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~-1 ~ ~-3 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~-2 ~ ~-3 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~-3 ~ ~-3 detect ~ ~ ~ potatoes 2 setblock ~~~ potatoes 3
execute @s ~3 ~ ~3 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~2 ~ ~3 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~1 ~ ~3 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~0 ~ ~3 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~-1 ~ ~3 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~-2 ~ ~3 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~-3 ~ ~3 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~3 ~ ~2 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~2 ~ ~2 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~1 ~ ~2 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~0 ~ ~2 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~-1 ~ ~2 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~-2 ~ ~2 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~-3 ~ ~2 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~3 ~ ~1 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~2 ~ ~1 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~1 ~ ~1 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~0 ~ ~1 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~-1 ~ ~1 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~-2 ~ ~1 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~-3 ~ ~1 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~3 ~ ~ detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~2 ~ ~ detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~1 ~ ~ detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~-1 ~ ~ detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~-2 ~ ~ detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~-3 ~ ~ detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~3 ~ ~-1 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~2 ~ ~-1 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~1 ~ ~-1 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~0 ~ ~-1 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~-1 ~ ~-1 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~-2 ~ ~-1 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~-3 ~ ~-1 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~3 ~ ~-2 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~2 ~ ~-2 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~1 ~ ~-2 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~0 ~ ~-2 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~-1 ~ ~-2 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~-2 ~ ~-2 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~-3 ~ ~-2 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~3 ~ ~-3 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~2 ~ ~-3 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~1 ~ ~-3 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~0 ~ ~-3 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~-1 ~ ~-3 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~-2 ~ ~-3 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~-3 ~ ~-3 detect ~ ~ ~ potatoes 1 setblock ~~~ potatoes 2
execute @s ~3 ~ ~3 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~2 ~ ~3 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~1 ~ ~3 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~0 ~ ~3 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~-1 ~ ~3 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~-2 ~ ~3 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~-3 ~ ~3 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~3 ~ ~2 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~2 ~ ~2 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~1 ~ ~2 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~0 ~ ~2 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~-1 ~ ~2 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~-2 ~ ~2 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~-3 ~ ~2 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~3 ~ ~1 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~2 ~ ~1 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~1 ~ ~1 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~0 ~ ~1 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~-1 ~ ~1 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~-2 ~ ~1 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~-3 ~ ~1 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~3 ~ ~ detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~2 ~ ~ detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~1 ~ ~ detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~-1 ~ ~ detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~-2 ~ ~ detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~-3 ~ ~ detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~3 ~ ~-1 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~2 ~ ~-1 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~1 ~ ~-1 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~0 ~ ~-1 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~-1 ~ ~-1 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~-2 ~ ~-1 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~-3 ~ ~-1 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~3 ~ ~-2 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~2 ~ ~-2 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~1 ~ ~-2 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~0 ~ ~-2 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~-1 ~ ~-2 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~-2 ~ ~-2 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~-3 ~ ~-2 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~3 ~ ~-3 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~2 ~ ~-3 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~1 ~ ~-3 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~0 ~ ~-3 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~-1 ~ ~-3 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~-2 ~ ~-3 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1
execute @s ~-3 ~ ~-3 detect ~ ~ ~ potatoes 0 setblock ~~~ potatoes 1