execute @s ~3 ~ ~3 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~2 ~ ~3 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~1 ~ ~3 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~0 ~ ~3 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~-1 ~ ~3 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~-2 ~ ~3 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~-3 ~ ~3 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~3 ~ ~2 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~2 ~ ~2 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~1 ~ ~2 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~0 ~ ~2 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~-1 ~ ~2 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~-2 ~ ~2 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~-3 ~ ~2 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~3 ~ ~1 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~2 ~ ~1 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~1 ~ ~1 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~0 ~ ~1 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~-1 ~ ~1 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~-2 ~ ~1 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~-3 ~ ~1 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~3 ~ ~ detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~2 ~ ~ detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~1 ~ ~ detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~-1 ~ ~ detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~-2 ~ ~ detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~-3 ~ ~ detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~3 ~ ~-1 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~2 ~ ~-1 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~1 ~ ~-1 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~0 ~ ~-1 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~-1 ~ ~-1 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~-2 ~ ~-1 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~-3 ~ ~-1 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~3 ~ ~-2 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~2 ~ ~-2 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~1 ~ ~-2 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~0 ~ ~-2 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~-1 ~ ~-2 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~-2 ~ ~-2 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~-3 ~ ~-2 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~3 ~ ~-3 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~2 ~ ~-3 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~1 ~ ~-3 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~0 ~ ~-3 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~-1 ~ ~-3 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~-2 ~ ~-3 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~-3 ~ ~-3 detect ~ ~ ~ wheat 6 setblock ~~~ wheat 7
execute @s ~3 ~ ~3 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~2 ~ ~3 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~1 ~ ~3 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~0 ~ ~3 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~-1 ~ ~3 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~-2 ~ ~3 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~-3 ~ ~3 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~3 ~ ~2 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~2 ~ ~2 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~1 ~ ~2 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~0 ~ ~2 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~-1 ~ ~2 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~-2 ~ ~2 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~-3 ~ ~2 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~3 ~ ~1 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~2 ~ ~1 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~1 ~ ~1 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~0 ~ ~1 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~-1 ~ ~1 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~-2 ~ ~1 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~-3 ~ ~1 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~3 ~ ~ detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~2 ~ ~ detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~1 ~ ~ detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~-1 ~ ~ detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~-2 ~ ~ detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~-3 ~ ~ detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~3 ~ ~-1 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~2 ~ ~-1 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~1 ~ ~-1 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~0 ~ ~-1 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~-1 ~ ~-1 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~-2 ~ ~-1 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~-3 ~ ~-1 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~3 ~ ~-2 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~2 ~ ~-2 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~1 ~ ~-2 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~0 ~ ~-2 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~-1 ~ ~-2 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~-2 ~ ~-2 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~-3 ~ ~-2 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~3 ~ ~-3 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~2 ~ ~-3 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~1 ~ ~-3 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~0 ~ ~-3 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~-1 ~ ~-3 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~-2 ~ ~-3 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~-3 ~ ~-3 detect ~ ~ ~ wheat 5 setblock ~~~ wheat 6
execute @s ~3 ~ ~3 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~2 ~ ~3 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~1 ~ ~3 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~0 ~ ~3 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~-1 ~ ~3 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~-2 ~ ~3 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~-3 ~ ~3 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~3 ~ ~2 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~2 ~ ~2 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~1 ~ ~2 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~0 ~ ~2 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~-1 ~ ~2 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~-2 ~ ~2 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~-3 ~ ~2 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~3 ~ ~1 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~2 ~ ~1 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~1 ~ ~1 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~0 ~ ~1 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~-1 ~ ~1 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~-2 ~ ~1 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~-3 ~ ~1 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~3 ~ ~ detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~2 ~ ~ detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~1 ~ ~ detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~-1 ~ ~ detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~-2 ~ ~ detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~-3 ~ ~ detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~3 ~ ~-1 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~2 ~ ~-1 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~1 ~ ~-1 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~0 ~ ~-1 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~-1 ~ ~-1 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~-2 ~ ~-1 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~-3 ~ ~-1 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~3 ~ ~-2 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~2 ~ ~-2 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~1 ~ ~-2 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~0 ~ ~-2 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~-1 ~ ~-2 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~-2 ~ ~-2 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~-3 ~ ~-2 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~3 ~ ~-3 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~2 ~ ~-3 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~1 ~ ~-3 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~0 ~ ~-3 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~-1 ~ ~-3 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~-2 ~ ~-3 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~-3 ~ ~-3 detect ~ ~ ~ wheat 4 setblock ~~~ wheat 5
execute @s ~3 ~ ~3 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~2 ~ ~3 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~1 ~ ~3 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~0 ~ ~3 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~-1 ~ ~3 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~-2 ~ ~3 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~-3 ~ ~3 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~3 ~ ~2 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~2 ~ ~2 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~1 ~ ~2 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~0 ~ ~2 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~-1 ~ ~2 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~-2 ~ ~2 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~-3 ~ ~2 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~3 ~ ~1 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~2 ~ ~1 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~1 ~ ~1 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~0 ~ ~1 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~-1 ~ ~1 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~-2 ~ ~1 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~-3 ~ ~1 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~3 ~ ~ detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~2 ~ ~ detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~1 ~ ~ detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~-1 ~ ~ detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~-2 ~ ~ detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~-3 ~ ~ detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~3 ~ ~-1 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~2 ~ ~-1 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~1 ~ ~-1 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~0 ~ ~-1 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~-1 ~ ~-1 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~-2 ~ ~-1 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~-3 ~ ~-1 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~3 ~ ~-2 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~2 ~ ~-2 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~1 ~ ~-2 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~0 ~ ~-2 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~-1 ~ ~-2 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~-2 ~ ~-2 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~-3 ~ ~-2 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~3 ~ ~-3 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~2 ~ ~-3 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~1 ~ ~-3 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~0 ~ ~-3 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~-1 ~ ~-3 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~-2 ~ ~-3 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~-3 ~ ~-3 detect ~ ~ ~ wheat 3 setblock ~~~ wheat 4
execute @s ~3 ~ ~3 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~2 ~ ~3 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~1 ~ ~3 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~0 ~ ~3 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~-1 ~ ~3 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~-2 ~ ~3 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~-3 ~ ~3 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~3 ~ ~2 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~2 ~ ~2 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~1 ~ ~2 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~0 ~ ~2 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~-1 ~ ~2 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~-2 ~ ~2 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~-3 ~ ~2 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~3 ~ ~1 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~2 ~ ~1 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~1 ~ ~1 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~0 ~ ~1 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~-1 ~ ~1 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~-2 ~ ~1 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~-3 ~ ~1 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~3 ~ ~ detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~2 ~ ~ detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~1 ~ ~ detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~-1 ~ ~ detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~-2 ~ ~ detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~-3 ~ ~ detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~3 ~ ~-1 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~2 ~ ~-1 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~1 ~ ~-1 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~0 ~ ~-1 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~-1 ~ ~-1 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~-2 ~ ~-1 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~-3 ~ ~-1 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~3 ~ ~-2 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~2 ~ ~-2 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~1 ~ ~-2 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~0 ~ ~-2 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~-1 ~ ~-2 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~-2 ~ ~-2 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~-3 ~ ~-2 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~3 ~ ~-3 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~2 ~ ~-3 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~1 ~ ~-3 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~0 ~ ~-3 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~-1 ~ ~-3 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~-2 ~ ~-3 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~-3 ~ ~-3 detect ~ ~ ~ wheat 2 setblock ~~~ wheat 3
execute @s ~3 ~ ~3 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~2 ~ ~3 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~1 ~ ~3 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~0 ~ ~3 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~-1 ~ ~3 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~-2 ~ ~3 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~-3 ~ ~3 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~3 ~ ~2 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~2 ~ ~2 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~1 ~ ~2 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~0 ~ ~2 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~-1 ~ ~2 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~-2 ~ ~2 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~-3 ~ ~2 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~3 ~ ~1 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~2 ~ ~1 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~1 ~ ~1 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~0 ~ ~1 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~-1 ~ ~1 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~-2 ~ ~1 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~-3 ~ ~1 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~3 ~ ~ detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~2 ~ ~ detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~1 ~ ~ detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~-1 ~ ~ detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~-2 ~ ~ detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~-3 ~ ~ detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~3 ~ ~-1 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~2 ~ ~-1 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~1 ~ ~-1 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~0 ~ ~-1 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~-1 ~ ~-1 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~-2 ~ ~-1 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~-3 ~ ~-1 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~3 ~ ~-2 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~2 ~ ~-2 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~1 ~ ~-2 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~0 ~ ~-2 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~-1 ~ ~-2 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~-2 ~ ~-2 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~-3 ~ ~-2 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~3 ~ ~-3 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~2 ~ ~-3 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~1 ~ ~-3 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~0 ~ ~-3 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~-1 ~ ~-3 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~-2 ~ ~-3 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~-3 ~ ~-3 detect ~ ~ ~ wheat 1 setblock ~~~ wheat 2
execute @s ~3 ~ ~3 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~2 ~ ~3 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~1 ~ ~3 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~0 ~ ~3 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~-1 ~ ~3 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~-2 ~ ~3 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~-3 ~ ~3 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~3 ~ ~2 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~2 ~ ~2 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~1 ~ ~2 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~0 ~ ~2 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~-1 ~ ~2 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~-2 ~ ~2 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~-3 ~ ~2 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~3 ~ ~1 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~2 ~ ~1 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~1 ~ ~1 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~0 ~ ~1 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~-1 ~ ~1 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~-2 ~ ~1 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~-3 ~ ~1 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~3 ~ ~ detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~2 ~ ~ detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~1 ~ ~ detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~-1 ~ ~ detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~-2 ~ ~ detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~-3 ~ ~ detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~3 ~ ~-1 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~2 ~ ~-1 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~1 ~ ~-1 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~0 ~ ~-1 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~-1 ~ ~-1 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~-2 ~ ~-1 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~-3 ~ ~-1 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~3 ~ ~-2 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~2 ~ ~-2 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~1 ~ ~-2 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~0 ~ ~-2 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~-1 ~ ~-2 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~-2 ~ ~-2 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~-3 ~ ~-2 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~3 ~ ~-3 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~2 ~ ~-3 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~1 ~ ~-3 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~0 ~ ~-3 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~-1 ~ ~-3 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~-2 ~ ~-3 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1
execute @s ~-3 ~ ~-3 detect ~ ~ ~ wheat 0 setblock ~~~ wheat 1